import './globals.css'

export const metadata = {
  title: "Rehaan's Next App",
  description: 'Generated by Rehaan Ansari',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
          {children}
      </body>
    </html>
  )
}
